services:
  go-server-1:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - GIN_MODE=release  # Example environment variabl
      - PORT=3001
    networks:
      - app-network # Set the network
  go-server-2:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - GIN_MODE=release  # Example environment variable
      - PORT=3001
    networks:
      - app-network # Set the network
  go-server-3:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - GIN_MODE=release  # Example environment variable
      - PORT=3001
    networks:
      - app-network # Set the network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"
      - "443:443"
    environment:
    - PORT=3001
    volumes:
      - ./nginx/ssl:/etc/nginx/ssl:ro 
    networks:
      - app-network

networks:
  app-network: